### ISSUE TITLE
Add GitHub Actions CI for Testing

### ISSUE THREAD

**Issue by raygervais** [Seneca-CDOT/satellite#2]
Let's add automated testing to this microservice foundation to ensure updates don't break functionality

**Comment by humphd** [comment]
I'm doing that now actually.  I'm about to test the npm publish workflow...

**Comment by humphd** [comment]
Testing and Release CI both done!

https://github.com/Seneca-CDOT/satellite/runs/1881928893?check_suite_focus=true

Running `npm version 1.0.x` locally and then `git push upstream master --tags` will do a release and publish to GitHub and npm.

https://www.npmjs.com/package/@senecacdot/satellite
