### ISSUE TITLE
Update release docs for Satellite

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/satellite#38]
We are using pnpm now, so it's different: 
ensure the master branch has green-go-ahead in CI
checkout `master`
`pnpm version v1.18.0 -m "Release v1.18.0"`
and then we do: 
`git push origin master --tags`
confirm the release is in the workflow

**Comment by humphd** [comment]
I lost this, as we don't usually file issues here.  Let's get this into our Telescope docs, cc @sirinoks.

**Comment by sirinoks** [comment]
I'm trying to file an issue in Telescope for this, but I don't fully get what it is about. I first thought we need to update the commands in readme from npm to pnpm, but I think this has something to do with releases and github actions, or.. `workflow`.. 
And I don't know where that is. Maybe it was even done already, cause there just was a release.
@AmasiaNalbandian 

Or anyone else who could explain it.

**Comment by sirinoks** [comment]
Or perhaps @rclee91, @JiaHua-Zou ?

**Comment by JiaHua-Zou** [comment]
On slack, I ask if there's a doc on how to release new patch and a link routed me to here.

**Comment by rclee91** [comment]
Yeah, this is describing how to make a release for Satellite. Just needs to be added to the documentation.

**Comment by menghif** [comment]
Closing in favour of https://github.com/Seneca-CDOT/telescope/issues/3390
